const categoriesTypes = {
    GET_ALL_DATA: "GET_ALL_DATA",
    GET_DATA_BY_CITY: "GET_DATA_BY_CITY",
    SORT_BY_RATING_HIGH_TO_LOW: "SORT_BY_RATING_HIGH_TO_LOW",
    SORT_BY_RATING_LOW_TO_HIGH: "SORT_BY_RATING_LOW_TO_HIGH",
    SORT_BY_NAME_A_Z: "SORT_BY_NAME_A_Z",
    SORT_BY_NAME_Z_A: "SORT_BY_NAME_Z_A",
    SORT_BY_PRICE_HIGH_TO_LOW: "SORT_BY_PRICE_HIGH_TO_LOW",
    SORT_BY_PRICE_LOW_TO_HIGH: "SORT_BY_PRICE_LOW_TO_HIGH",
    DELETE_ITEM_FROM_DATA: "DELETE_ITEM_FROM_DATA",
    ADD_ITEM_TO_DATA: "ADD_ITEM_TO_DATA"
};

export default categoriesTypes;